routes/web.php
 <?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

// First test for routing
Route::get('/rooms', function () {
    $rooms = \App\Models\Room::all();
    return view('admin/location/rooms/index', ['rooms' => $rooms]);
});

Route::namespace('Admin')->prefix('admin')->middleware('auth')->group(function () {
    // Controllers Within The "App\Http\Controllers\Admin" Namespace
    // URL prefix by "admin."

    // Location
    Route::namespace('Location')->prefix('location')->group(function () {
        // Controllers Within The "App\Http\Controllers\Admin\Location" Namespace
        // URL prefix by "admin.location."

        Route::resource('rooms', 'RoomController');
    });

    Route::resource('departments', 'DepartmentsController');

    Route::resource('skills', 'SkillController');
});

Route::group(['prefix' => 'profile',  'middleware' => 'auth'], function () {
    Route::get('/', 'ProfileController@show')->name('profile.show');
    Route::get('/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('/update', 'ProfileController@update')->name('profile.update');
});

# Social Login
Route::get('/login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider','facebook');
Route::get('/login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider','facebook');


# Tho Routes
Route::prefix('admin')->middleware('auth')->group(function() {
    Route::group([
        'namespace' => 'Admin'
    ], function() {
        Route::get('/users', 'UserController@index')->name('admin.users');

        Route::group([
            'prefix' => 'datatables',
            'as' => 'datatables::'
        ],function(){
            Route::get('users', 'UserController@datatableUserList')->name('users');
        });
    });



    Route::get('/{route}', 'AdminController@index');
    Route::get('/{route}/{subroute}', 'AdminController@index');
    Route::get('/{route}/{subroute}/{action}', 'AdminController@index');
    Route::get('/{route}/{subroute}/{id}/{action}', 'AdminController@index');
});

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Room extends Model
{
    /**
     * Return the empty seat of the room
     *
     * --> Move to repository later
     */
    public function emptySeat()
    {
        $seated = User::where('room_id', $this->id)->count();

        return $this->capacity - $seated;
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'code', 'description', 'capacity',
    ];
}

app/Http/Controllers/Admin/Location/RoomController.php
<?php

namespace App\Http\Controllers\Admin\Location;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use App\Http\Controllers\Controller;
use App\Models\Room;
use App\Repositories\Interfaces\RoomRepositoryInterface;
use App\Repositories\Eloquents\RoomRepositoryEloquent;
use App\Repositories\RoomRepository;

class RoomController extends Controller
{
    protected $roomRepositorySimple;
    protected $roomRepositoryComplex;

    public function __construct(
        RoomRepository $roomRepositorySimple,
        RoomRepositoryInterface $roomRepositoryComplex
    ) {
        $this->roomRepositorySimple = $roomRepositorySimple;
        $this->roomRepositoryComplex = $roomRepositoryComplex;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Use Eloquent model
        //$rooms = Room::paginate(5);

        // use simple repo
        $rooms = $this->roomRepositorySimple::paginate(5);

        // use complex repo
        //$rooms = $this->roomRepositoryComplex->paginate(5);

        return view('admin/location/rooms/index')->with('rooms', $rooms);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/location/rooms/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validate inputs
        $request->validate([
            'code'      => 'required|unique:rooms|max:255',
            'capacity'  => 'required|integer',
        ]);

        try {
            // Save new record
            if ($this->roomRepositorySimple->create($request->all())) {
                // Flash a successful message
                $request->session()->flash('status', [
                    'type' => 'success',
                    'message' => 'Room was created successful!'
                ]);
            } else {
                throw new \Exception('Cannot store room data');
            }
        } catch (\Exception $e) {
            // Log error
            Log::error($e->getMessage());

            // Flash a error message
            $request->session()->flash('status', [
                'type' => 'danger',
                'message' => 'Cannot store room data'
            ]);
        }

        // Back to list page with flash message
        return redirect()->route('rooms.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function show(Room $room)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function edit(Room $room)
    {
        return view('admin/location/rooms/edit')->with(compact('room'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Room $room)
    {
        $room->save();

        /*
        $request->session()->flash('status', [
            'type' => 'warning',
            'message' => 'Room was updated successful!'
        ]);
        */

        flash('Room was updated successful!')->warning();
        flash('Room was updated successful!')->error();
        flash('Room was updated successful!')->success();

        return redirect()->route('rooms.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Room  $room
     * @return \Illuminate\Http\Response
     */
    public function destroy(Room $room)
    {
        //
    }
}

resources/views/admin/location/rooms/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">New Room</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('rooms.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="code" class="col-md-4 col-form-label text-md-right">{{ __('Code') }}</label>

                            <div class="col-md-6">
                                <input id="code" type="text" class="form-control{{ $errors->has('code') ? ' is-invalid' : '' }}" name="code" value="{{ old('code') }}" required autofocus>

                                @if ($errors->has('code'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-6">
                                <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" value="{{ old('description') }}" required></textarea>

                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="capacity" class="col-md-4 col-form-label text-md-right">{{ __('Capacity') }}</label>

                            <div class="col-md-6">
                                <input id="capacity" type="text" class="form-control{{ $errors->has('capacity') ? ' is-invalid' : '' }}" name="capacity" value="{{ old('capacity') }}" required>

                                @if ($errors->has('capacity'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('capacity') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/location/rooms/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Room</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('rooms.update', $room->id) }}">
                        @method('PUT')
                        @csrf

                        <div class="form-group row">
                            <label for="code" class="col-md-4 col-form-label text-md-right">{{ __('Code') }}</label>

                            <div class="col-md-6">
                                <input id="code" type="text" class="form-control{{ $errors->has('code') ? ' is-invalid' : '' }}" name="code" value="{{ $room->code }}" required autofocus>

                                @if ($errors->has('code'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="capacity" class="col-md-4 col-form-label text-md-right">{{ __('Capacity') }}</label>

                            <div class="col-md-6">
                                <input id="capacity" type="text" class="form-control{{ $errors->has('capacity') ? ' is-invalid' : '' }}" name="capacity" value="{{ $room->capacity }}" required>

                                @if ($errors->has('capacity'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('capacity') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/location/rooms/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            {{-- $rooms->links() --}}
            <div class="card">
                <div class="card-header">Room List</div>

                <div class="card-body">
                    <table border="1">
                        <thead>
                            <th>Id</th>
                            <th>Code</th>
                            <th>Capacity</th>
                            <th>Empty Seat</th>
                            <th>Description</th>
                            <th>Edit</th>
                        </thead>
                        <tbody>
                            @foreach ($rooms as $room)
                            <tr>
                                <td>{{ $room->id }}</td>
                                <td>{{ $room->code }}</td>
                                <td>{{ $room->capacity }}</td>
                                <td>{{ $room->emptySeat() }}</td>
                                <td>{{ $room->description }}</td>
                                <td><a href="{{ route('rooms.edit', $room->id) }}">Edit</a></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection