routes/web.php
 <?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

// First test for routing
Route::get('/rooms', function () {
    $rooms = \App\Models\Room::all();
    return view('admin/location/rooms/index', ['rooms' => $rooms]);
});

Route::namespace('Admin')->prefix('admin')->middleware('auth')->group(function () {
    // Controllers Within The "App\Http\Controllers\Admin" Namespace
    // URL prefix by "admin."

    // Location
    Route::namespace('Location')->prefix('location')->group(function () {
        // Controllers Within The "App\Http\Controllers\Admin\Location" Namespace
        // URL prefix by "admin.location."

        Route::resource('rooms', 'RoomController');
    });

    Route::resource('departments', 'DepartmentsController');

    Route::resource('skills', 'SkillController');
});

Route::group(['prefix' => 'profile',  'middleware' => 'auth'], function () {
    Route::get('/', 'ProfileController@show')->name('profile.show');
    Route::get('/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('/update', 'ProfileController@update')->name('profile.update');
});

# Social Login
Route::get('/login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider','facebook');
Route::get('/login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider','facebook');


# Tho Routes
Route::prefix('admin')->middleware('auth')->group(function() {
    Route::group([
        'namespace' => 'Admin'
    ], function() {
        Route::get('/users', 'UserController@index')->name('admin.users');

        Route::group([
            'prefix' => 'datatables',
            'as' => 'datatables::'
        ],function(){
            Route::get('users', 'UserController@datatableUserList')->name('users');
        });
    });



    Route::get('/{route}', 'AdminController@index');
    Route::get('/{route}/{subroute}', 'AdminController@index');
    Route::get('/{route}/{subroute}/{action}', 'AdminController@index');
    Route::get('/{route}/{subroute}/{id}/{action}', 'AdminController@index');
});

app/Models/Skill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    protected $table = "skills";

     protected $fillable = [
        'title', 'description', 'priority', 'created_at', 'updated_at'
    ];

    /*public static function scopePrioritize($query)
    {
        return $query->orderBy('priority', 'asc');
    }*/
}

app/Http/Controllers/Admin/SkillController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Skill;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Eloquents\SkillRepository;

class SkillController extends Controller
{
    /**
     * @var SkillRepositoryInterface|\App\Repositories\Repository
     */
    protected $skillRepository;

    public function __construct(SkillRepository $skillRepository)
    {
        $this->skillRepository = $skillRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $skills = $this->skillRepository->paginate(3);
        return view('admin/skills/index', ['skills' => $skills]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/skills/create');
    }

    /**
     * Validation title and description 
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validation request
        $validate = $request->validate([
            'title' => 'required|unique:skills|min:2|max:20',
            'description' => 'required|max:1024',
        ]);
        try {
            // Save new record
            if ($this->skillRepository->create($request->all())) {
                // Flash a successfully message
                $request->session()->flash('status', [
                    'type' => 'success',
                    'message' => 'Successfully create the skill!'
                ]);
            } else {
                throw new \Exception('Cannot create skill data');
            }
        } catch (Exception $e) {
            // Log error 
            Log::error($e->getMessage());
            // Flash a error message
            return back()->session()->flash('status', [
                'type' => 'danger',
                'message' => 'Create the skill error!'
            ]);
        }
        // Back to list page with flash message
        return redirect('admin/skills');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Skill $skill)
    {
        return view('admin.skills.edit', compact('skill', $skill));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //var_dump($request);die();
        // Validation request.
        $request->validate([
            'title' => 'required|min:2|max:20|unique:skills,title,'.$id,
            'description' => 'required|max:1024',
        ]);
        try {
            // Update record
            if ($this->skillRepository->update($id, $request->all())) {
                // Flash a update successfully
                $request->session()->flash('status', [
                    'type' => 'success',
                    'message' => 'Successfully update the skill!'
                ]);
            } else {
                throw new \Exception('Cannot update skill data');
            }
        } catch (Exception $e) {
            // Log error
            Log::error($e->getMessage());
            // Flash a update error
            return back()->session()->flash('status', [
                'type' => 'danger',
                'message' => 'Update the skill error!'
            ]);
        }
        // Back to list page with flash message
        return redirect('admin/skills');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            // Delete a record
            if ($this->skillRepository->delete($id)) {
                // Flash message with delete success
                $request = session()->flash('status', [
                    'type' => 'success',
                    'message' => 'Delete create the skill!'
                ]);
            } else {
                throw new \Exception('Cannot delete skill data');
            }
        } catch (Exception $e) {
            // Log error
            Log::error($e->getMessage());
            // Flash a update error
            return back()->session()->flash('status', [
                'type' => 'danger',
                'message' => 'Delete the skill error!'
            ]);
        }
        // Back to list page with flash message
        return redirect('admin/skills');
    }
}

resources/views/admin/skills/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><span>Add Skill</span> <a class="btn btn-primary" style="float: right;" href=".">Back</a></div>
                <!-- @foreach ($errors->all() as $error)
                    <div class="btn btn-danger alert alert-{{ session('status.type') }} alert-dismissable">
                        {{$error}}
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    </div>
                @endforeach -->
                <form style="width: 80%; margin: 0 auto;" method="post" action="{{url('admin/skills')}}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Title</label>
                        <input type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" value="{{ old('title') }}" id="title" name="title" aria-describedby="title" placeholder="Enter title" require>
                        @if ($errors->has('title'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Decription</label>
                        <textarea class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" id="title" name="description" aria-describedby="decription" placeholder="Enter decription" require>{{ old('description') }}</textarea>
                        @if ($errors->has('description'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                    </div>
                    <button style="margin-left: 50%; margin-bottom: 10px" type="submit" name="btnsubmit" class="btn btn-primary">Create Skill</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/skills/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><span>Edit Skill</span> <a class="btn btn-primary" style="float: right;" href="/admin/skills">Back</a></div>
                <!-- @foreach ($errors->all() as $error)
                    <div class="btn btn-danger alert alert-{{ session('status.type') }} alert-dismissable">
                        {{$error}}
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    </div>
                @endforeach -->
                <form style="width: 80%; margin: 0 auto;" method="POST" action="{{url('admin/skills', $skill['id'])}}">
                    @method('PUT')
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{__('Title')}}</label>
                        <input type="text" value="{{ old('title') ? old('title') : $skill->title }}" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" id="title" name="title" aria-describedby="title" placeholder="Enter title" require>
                        @if ($errors->has('title'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{__('Decription')}}</label>
                        <textarea class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" placeholder="Enter decription" require>{{ old('description') ? old('description') : $skill->description }}</textarea>
                        @if ($errors->has('description'))
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                    </div>
                    <button style="margin-left: 50%; margin-bottom: 10px" type="submit" name="btnsubmit" class="btn btn-primary">{{ __('Edit Skill') }}</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/skills/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Skill infornation</div>
                <!-- @if (session('status.message')) 
                <div class="alert alert-{{ session('status.type') }} alert-dismissable">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {{ session('status.message') }}
                </div>
                @endif -->
                <div class="card-body">
                    <a class="btn btn-primary" href="{{ route('skills.create') }}">Add Skill</a>
                    <table border="0" class="table">
                        <thead>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Created At</th>
							<th>Updated At</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </thead>
                        <tbody>
                            @foreach ($skills as $skill)
                            <tr>
                                <td>{{ $skill['title'] }}</td>
                                <td>{{ str_limit($skill['description'], 50) }}</td>
                                <td>{{ $skill['created_at'] }}</td>
								<td>{{ $skill['updated_at'] }}</td>
                                <td><i class="fas fa-edit" style="margin-right: 10px;"></i><a class="btn btn-warning" href="{{ route('skills.edit', $skill->id) }}">Edit</a></td>
                                <td>
                                    <form action="{{url('admin/skills', $skill['id'])}}" method="POST">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <i class="fas fa-trash-alt" style="margin-right: 10px;"></i><input type="submit" class="btn btn-danger" value="Delete"/>
                                    </form>
                                </td>
                            </tr>
                            @endforeach 
                        </tbody>
                    </table>
                </div>
                <div style="margin: 0 auto;">{{ $skills->links() }}</div>
            </div>
        </div>
    </div>
</div>
@endsection